// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppState() {
  return window['go']['backend']['App']['GetAppState']();
}

export function GetDirectoryDiffDetails() {
  return window['go']['backend']['App']['GetDirectoryDiffDetails']();
}

export function OpenNewRepo() {
  return window['go']['backend']['App']['OpenNewRepo']();
}

export function ReadFile(arg1) {
  return window['go']['backend']['App']['ReadFile'](arg1);
}
