// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function CleanupTerminalSession(arg1:string):Promise<void>;

export function ClearApplicationLogHistory():Promise<void>;

export function CloseRepo(arg1:string):Promise<backend.App>;

export function EndDiffSession(arg1:string):Promise<void>;

export function GetAppState():Promise<backend.App>;

export function GetApplicationLogHistory():Promise<Array<backend.LogEntry>>;

export function GetBranches(arg1:string):Promise<Array<backend.GitRef>>;

export function GetDefaultShellCommand():Promise<string>;

export function GetDetailedCommitInfo(arg1:string,arg2:string):Promise<backend.DetailedCommitInfo>;

export function GetDiffSession(arg1:string):Promise<backend.DiffSession>;

export function GetStartupDirDiffDirectory():Promise<backend.Directory>;

export function GetTags(arg1:string):Promise<Array<backend.GitRef>>;

export function GitFetch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InitNewTerminalSession(arg1:string):Promise<void>;

export function ListDiffSessions():Promise<Array<backend.DiffSession>>;

export function OnTerminalSessionWasResized(arg1:string,arg2:backend.TTYSize):Promise<void>;

export function OpenNewRepo():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RunGitLog(arg1:string):Promise<Array<backend.GitLogCommitInfo>>;

export function RunGitLogFromRef(arg1:string,arg2:string):Promise<Array<backend.GitLogCommitInfo>>;

export function RunGitLogWithOptions(arg1:string,arg2:backend.GitLogOptions):Promise<Array<backend.GitLogCommitInfo>>;

export function SearchCommits(arg1:string,arg2:string):Promise<Array<backend.GitLogCommitInfo>>;

export function StartDiffSession(arg1:backend.DiffOptions):Promise<backend.DiffSession>;

export function Startup(arg1:context.Context,arg2:backend.StartupState):Promise<void>;

export function ToggleStarRepo(arg1:string):Promise<boolean>;

export function UpdateSettings(arg1:backend.AppSettings):Promise<void>;
