// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CloseRepo(arg1:string):Promise<backend.App>;

export function GetAppState():Promise<backend.App>;

export function GetDirectoryDiffDetails():Promise<backend.Directory>;

export function IsInDirDiffMode():Promise<boolean>;

export function OpenNewRepo():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;
