// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupStagingDiffSession(arg1) {
  return window['go']['backend']['App']['CleanupStagingDiffSession'](arg1);
}

export function CleanupTerminalSession(arg1) {
  return window['go']['backend']['App']['CleanupTerminalSession'](arg1);
}

export function ClearApplicationLogHistory() {
  return window['go']['backend']['App']['ClearApplicationLogHistory']();
}

export function CloseRepo(arg1) {
  return window['go']['backend']['App']['CloseRepo'](arg1);
}

export function CommitChanges(arg1, arg2) {
  return window['go']['backend']['App']['CommitChanges'](arg1, arg2);
}

export function CreateStagingDiffSession(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateStagingDiffSession'](arg1, arg2, arg3);
}

export function DeleteCustomCommand(arg1) {
  return window['go']['backend']['App']['DeleteCustomCommand'](arg1);
}

export function EndDiffSession(arg1) {
  return window['go']['backend']['App']['EndDiffSession'](arg1);
}

export function ExecuteShellCommand(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ExecuteShellCommand'](arg1, arg2, arg3);
}

export function GetAllRefs(arg1) {
  return window['go']['backend']['App']['GetAllRefs'](arg1);
}

export function GetAppState() {
  return window['go']['backend']['App']['GetAppState']();
}

export function GetApplicationLogHistory() {
  return window['go']['backend']['App']['GetApplicationLogHistory']();
}

export function GetDefaultShellCommand() {
  return window['go']['backend']['App']['GetDefaultShellCommand']();
}

export function GetDetailedCommitInfo(arg1, arg2) {
  return window['go']['backend']['App']['GetDetailedCommitInfo'](arg1, arg2);
}

export function GetDiffSession(arg1) {
  return window['go']['backend']['App']['GetDiffSession'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['backend']['App']['GetGitStatus'](arg1);
}

export function GetStartupDirDiffDirectory() {
  return window['go']['backend']['App']['GetStartupDirDiffDirectory']();
}

export function GetWorktrees(arg1) {
  return window['go']['backend']['App']['GetWorktrees'](arg1);
}

export function GitFetch(arg1) {
  return window['go']['backend']['App']['GitFetch'](arg1);
}

export function InitNewTerminalSession(arg1) {
  return window['go']['backend']['App']['InitNewTerminalSession'](arg1);
}

export function ListDiffSessions() {
  return window['go']['backend']['App']['ListDiffSessions']();
}

export function OnTerminalSessionWasResized(arg1, arg2) {
  return window['go']['backend']['App']['OnTerminalSessionWasResized'](arg1, arg2);
}

export function OpenNewRepo() {
  return window['go']['backend']['App']['OpenNewRepo']();
}

export function OpenRepoWithPath(arg1) {
  return window['go']['backend']['App']['OpenRepoWithPath'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['backend']['App']['ReadFile'](arg1);
}

export function RunGitLog(arg1, arg2) {
  return window['go']['backend']['App']['RunGitLog'](arg1, arg2);
}

export function SaveCustomCommand(arg1) {
  return window['go']['backend']['App']['SaveCustomCommand'](arg1);
}

export function StageAllFiles(arg1) {
  return window['go']['backend']['App']['StageAllFiles'](arg1);
}

export function StageFile(arg1, arg2) {
  return window['go']['backend']['App']['StageFile'](arg1, arg2);
}

export function StartDiffSession(arg1) {
  return window['go']['backend']['App']['StartDiffSession'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['backend']['App']['Startup'](arg1, arg2);
}

export function ToggleStarRepo(arg1) {
  return window['go']['backend']['App']['ToggleStarRepo'](arg1);
}

export function UnstageAllFiles(arg1) {
  return window['go']['backend']['App']['UnstageAllFiles'](arg1);
}

export function UnstageFile(arg1, arg2) {
  return window['go']['backend']['App']['UnstageFile'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['backend']['App']['UpdateSettings'](arg1);
}

export function ValidateRef(arg1, arg2) {
  return window['go']['backend']['App']['ValidateRef'](arg1, arg2);
}
