// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function GetAppState():Promise<backend.App>;

export function GetDirectoryDiffDetails():Promise<backend.Directory>;

export function OpenNewRepo():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;
